apiVersion: v1
kind: ConfigMap
metadata:
  name: techleads-example-data
  namespace: namespacea
  labels:
    app: techleads-example
    version: techleads-example
data:
  data.json: |-
    {
      "usernameDb" : "teste",
      "information" : "placeholder",
      "type" : "kubernetes"
    }